####################################################################################################
# argocd-dev
####################################################################################################
FROM argocd-base
COPY argocd /usr/local/bin/

USER root
RUN ln -s /usr/local/bin/argocd /usr/local/bin/argocd-monorepo-repo-server && \
    ln -s /usr/local/bin/argocd /usr/local/bin/argocd-monorepo-controller

USER 999
